dist: trusty
sudo: false
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  sonarqube: true
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
env:
  global:
    secure: d+wUKpU33D91JsBhpEsczeFZqgUFQ2nuEU8AX00Ti6tOdraxBznuSJOv7YoPJa06BNYW9+rIi7hruW+2gsCWyE0T10ps+NMdMzQPxS1ofAYy0JrRDA1F3jpv9/8DbXzhMsejTB67Txp8z2EvDFK2EGE9BEmcKV3vfJqihPycEMgreSEMYP2DgXXwyWrmcehLWJZ3t7BxZJ3XN5gxsifdE/L03VKHg6oMOWTTOiceqeecPWz81Lw1kXballXA+pnZjHaoim8zbkSINYbrgXxA8WX7ItWKsAwR3M8TWIs4B7gdi0FT+tyqYtfDWHJ16JJW/L6umPq1wOmUlbryfRLPBYv29KShET5007yfsM67lmYczPr8DogvOeJvs0HFNJh5PJ0XpVKqB88ecEum0GCksr+y4HY97cKjnM1U1hboVCf5Wb9gmx4m2/LSSzjaJywi9xdACvOWS28e+50h4N6vJYC/zOkhD+MGFwbAukcNrM2KwTDoqgHxR80sFrlvYFChTaOdvEPoFWiB0j33wFj4UoecSzzko+nsF2I2am5V61P0BYkeQasfsfsDeQE2FrxQEEOppBrvgtsLauQFuMNXe+al8XDov0g/GveKtnNnRFtCxJsMi8+xFEnAzi118VB00oQ1qlNjh1faZhfdTDzXFgv5IZt7+ApsIarLvA0El9o=
