dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
    secure: BjLD4kTtEO9XOspo9EkRKZENBWIZq0RFjd5hzEWzsLMf98APBC7ae/u+GFKAIfIbGUN9y3h+l/nKYZGhyzg5lW0BVAQLB9958wbSx0ZVan7hLZ6mDJsA8GdwW5dMDxSkp2BQfKkQZigOISVFjzhZQR1qaUENqIiEM7v2AE3DnbWt6y8rU8ZB/rwozPSE+uB15NrAMlnKTWz291OzRf7S6kwlZMXu6eHlCgKYhUuYMA4Ouyqt8otOMOisF9SymgR1w+5LxNRdq4pdkhxbyS/ZTtSZRW4a6xr0325dIRBrQQ/XsUkbuOAk9A/rqo0zktbc2RW6wqg2+c0UxQ5kpNc4MB0yU5U6KsZ9iC0Xd7/wEDgTOdXCE1QDRIcUIlqwMphqdWwjqq68Z68CVAyox9CJV7i9ljO1GOQyDkcSlgx2Ub3c3+K0Wy1HTRDrC+OMm6VPzf1iem1/Lmnhzr6gy4kEb3gnYXyzHRPmZ6GOI3Rjyb0vJVuEnEZiQqDhhHl7gCyZrLz/vkuv8F1AxYg51Q36aN0+8De3brqdSYMhtNc94Qocm4dxQhCLYY13qmXlERToXHYt34OQZ+A7wA/5lVLUDMYCKAklBuj1RfSIAoRzKtLkeg+EVAze1odwbzMinYIlyJIKhInHVgCN9dyNXSSYyzsiSG33IuTQ1WkoF8EjFSk=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
