dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
    secure:"HbcvUoAIMz/d/AOufoWYjO5IpptO5cMaXjFqWHfRnQ4o+H0Pd0g057WtRXQVuLfIsrznbuSMG5nIbqwmAg4cYQxWv76JYDJfhIbZRUqf5JredvdbolYylXQDPHbc120WExRXrAHX9EFc/oUMfWa7Q4oZtCGxsCVgCXJOW0fCpt1K/9dHGsqQVJID0GICq4tWvkZ4DRcyhgha4iNgpNVB9gShk6H+3gyxBQvZKQi3UGxVHp2QkBJSBgVl+CsW2j2GSrpYCic/B1A9exNl9yhMh9lmwYt7izk1+R6MMXx8xYZsxIyCGy8+usyC0GdUcviazXX6E/VaLPjHZXhjuI0X90KoB3GN0D6q/hA9L8dFcy/fTO/SJI1RVxQFcCQEdR/EJuj/f6JCzKt1Sg7LZvlF/b+k415PaYEmzRN+OAVFY6CjTPky8W1Ux04j0h+Yd11WdR1u2LGGMEFK309HChTQ0JjoHQ8u0WymDbBxlwc3q9Hgy0MsaEFDzrVFbMw9+5ohSLJJR0phZh8P9B/R3KsTujwh2qSCockDmsNuw5hCPE6LRoyP6e1OSQMV1tjiGqQ4gKZH6XK4MFFrPyyuivyOXD/TiX6NcRGcgLEM+rnibEmq7IUr2byh2wYxJm+4IyCuVuXkOwVg2LxAuGg7gg/y1T0iOfJepG6GEmTgi3/+j+Q="
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=${SONAR_TOKEN}
