dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
    secure: p8OEPuaVSBUt4ATk2p6IPiLqIYNDejAwZzyyqEKqwcynJCRMQevb9IQDT3KRO9zq926OJF8/4pFmImKso/3wuBTHjvg3PBQMxxsFQmR308kdVxEV0TvU4ZmVxGficHiJ4Bk4t5ExhLkBQT5oby9QEUTqpj3l7jfQwZcB8FW08oePbikrYHlw0vgbATTaeEKdfT3Dig2PT8XodEqSh/g8DvaXaJ4SOZ0JsLau2Qg145DuH3ZJDRvkEP5bSCaTG6riFOJrXHhf3QGiHQUztDlkKRoGy17fs+BHctib+L3HGjKXPCE18bAaA4PTDwLpQSW7L2zsTEhRSZWWBNtK21881hZYKaj1fireESIdpx1ErqxBFQM5NR7u4oOsZHHF0RIQmWOq9hIfqtJecSxS+h8wE57v1l4Ntzi2mam+hQ60T2XFKhZa4c757tO51FzHslKgabY/xonc0QKFpxhxgCcgmzUz+M6vtX6i+sqGiC4GICXq3g1d92aSvAe8mvfWyfya0tsH0xt+JetzkBNBIkTWZG4nVX5b2jxwJjQmA9jzO10AbloogP+bL0t9wR3PuJH2RkIsYgOQdCCCcLFpGSEeYQlSpJRxOqsroycAJDi4j9QbUFHOIkg0d8Ivh3NzZhhB1sqsdgDoIqm/eb54bqdnQVWRi+8QcY7j/jbHsuwqy5A=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
