dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
    secure: fy3GqayZqlgVhESvwf4hEEZNl5oCtfLcYgJMIw2tQIYl70XnsWVwHckVTMbSoYASOCnVZf4vsmvH13Mwo7pka1f9G6i4uHpCbxCYIdNe886wDLrpEiUsXwmeFIDwcXsHAJKtd/X3QDOgauskfARMe0JhK7kTvu31OoKK9TV02IbhtdLCUCiLthiEE5kEehwkuMVvU88YDa2aXoSQJCLX3s4KLrimFw7QvUTseMaw25XPfVvh/IZiKo5Z5qLgFJB4FXK8apJI4ob9RCqrnEpsVRMsrrPBfPfH/oVMEL+zQWDe2P21xoZeS6Eaubpoh1YnO4hey8saQ34u7xCBoLrWgYdQtJpEmYeuxnSR3g3dIGxWxJcRF4uNXpMV6qIoF+CHnlrEPEfG2t56yZV0WPW4AolNX7AeHXeZsddjN0gSYbJHBJUMSik9F9ysibLYBS/pYggef9XpHpW+WIVFCgQWRc/MtoSuiNyC3+ig/0IvCVAOoU8OCIR+q4g6NZ8a83hQO95sed2kS7vn4MT9MtXNv5XxsqykyKebukCPxOdJEfYV42rGzxjAoLoQdJ8urJ1Jkd4J2yZeB4UWx+78Go7D1Eo0SX9FrErGYhwfcKEscgN/CECCFU8gJq/kevENYy3NObVo+kandtv9Gd4CMeoqeyA9/UtDS9cIhR7WiaeEq94=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
