dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
    secure: n+fnrPd+jU/HYWFH8MfBAjAb1/GPBXue9E3pd8HrNiamdzC9JEt2F+ooIArud23vYFFyDEZBB4UEZG0pe2esQpgL9mjvZhVJOQwG0hqvdiv9C24x7116ynOWtMnf7SsFqapbDUj+chRlTD8XdCdaoAuOoqXz8ltWe2ns6IInn8uiFeyvAgNBNiDGKLVINQZ4lHp8QiQWYHsQS1UsZhVNP8hfE75s2G4lEz+7KJizSX63bQlrGpKliMF/q8mydZ/bfurwFzdjAhnvPDmXRvoQUmvra/IZFHhmDGCUeVY87ACCuuOII4fu+WQOHGDWcm3MiFSExHfu3kbRR87L+weACSBYDTNx0ghJ2qkXCZJCE49meBZLE39w0pTEFOONhXZZXMoowT0HlQbfFUy1zqStnnIQKEW07wUMx1Aws81ENmjSFo0e5ZJPC/KEiTIaukvszQ0Vk94GDdYckTCGwY26MtKWehWaMXhI3LRtWAeCwgDPozo3vhW4R1feHxSZznn6Wng9SCQ62X63gzdqYWC6WhXxAreIe5bmmmvDTr8H7YCaNkYhaE1D7fJOmpfOKVqbufmrv7uU1VeZq2CZ9yfSeREZ1jWOwGQFA5Obev87SQqoPUvi+78cuPSwIR4Q3O8gxMkZZcj27AiyHdOaBK8Y3vMjz8yKPqu0hX0ZZskUoJY=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login='$SONAR_TOKEN'
