dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
  - secure: HuysorfXZMkjTXIXkZbHpsBgylqosbavHWKAUYJ1EajlaOR/1OmJ6TOXHE9sziIwfphkJr6SNJ24uuKk493a9jjY6P1MqbEiA5aQDhTQ8Bs2UoDySZQLdi9f3trru5UpKYAdrV27+NTHuDTNQhIywSRjYN1cDxZA8zdPf21bhTfT9tY83qHdsUKdvtm4joMCf9pHMaXsSldxbvMZyyAwlRaiTKUCH3nYlAKjkw/QDG4U35qf98NMazvlVjjZu8vTchJMs+xP2wmJkicleDcrWshTHlfDRZ1la01ixpQNJM8mwjUou4AXrdNpnSNAjn8sX4zcP5kd27gVugTQMRdi1jQ482bX49ABvNMHJz8toAtFVsbPYaFrdYiV4T9tQjfs8qBOlIKucLnav7kqCzyHhcoiZZI6ro3fEHajn2W/nGSc9JehXwXZi7jmHKPtiJ1MZ4gSFsdjX02kLNLJo0/mgSgQgIYVtOStGvYAO8Vq7Ycbg5SLZNCcDy4UJcBDOw0Y9qeHIExfbftW/gjKZaGxQl+LEymT1zoK4d/6SuA25Hc+VxAzUxzCAWkS55Cf51ixNTpeaYwrfIulg7GFlcy3v3HewrLE4MUF66bqOIDgL9RRfMM5sPOP6Cbb1ctG7/1YXPIISa1MemO8t3RZknoORAo3rsqZ3mtKYgCER6XfTf8=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
