dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
    secure: YzkzfIZ02qXAMwG5FsLJEV8K2HxF5kQdxy8mx7bOQc/A3ZohcqvTmOCZI4hAhy24P/0obDLBrr8Ewx8OIegcaM4UfW7Dpuy7Nu6O461b/SLQ8LzEgibRwIsiMb+bf8aeL5nu9q9q3PY0/jsC0zIQ6OEGBrSYTCiNoNW5+pT93gMC1eo+Xw568sMT0YKlKmLMC61OX5MbGTnMG0hWRC3CsIFpdWcFaGhvHpJLWQ9Cvx2W1tCWcZv4Eeu8cM6dB5WH3amPDwdeBnPIENJI3tdycGJok+FBgOLko2PzSdVD2k+iQoD4bO8wb0IGpcA7HOTlEuQ/bP0O8/vMVzp5Y8I9yJQOa7CdmEJCohjnl26zFLKSCbZViG7C4V2cwJHCC80e1tqiMbZ2ni7HDrUr4fOeW/2ZAkY5nK/FbK2hfPqLLyquYy4xTH1WZ1W/NjLhXuZsZGHoBmcxjUO1tfY451lqkvR7J6zmoRYyahLSJEFRLrEzZwZo831Zi9798J1ZN9Y7Jyi8A3wm56sakPLMNMSwX9FF3rPjUwJuotR9g1oXMT4I2BgfQJbv9Y8qUX8+5KOglPhLjgZnOvD5C+yw+Yb7BrrjyMLNpKIEz1K7jBIL9zE7R5K6KcnnroOD3TnHyxtLbd1QwZX1bNLXXMIV6OYA6sslU2b4ZdQVn4oUhS/EHDM=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
