dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube:
    token: 1abeb36b5e88237bb32d141cfb832530df398359 dwAO0K/zdHk69DrIMeHGzzE2Ze/NrxuN37aIAYRhWCFqc1kswM1RRw9+Z3JgjlhGoaYNOyaKFBQ427l2mmQDks5zusO4c1uz7YzeAePUF8YM0d2Qab4DpPtzGCL0w/assQEOD2faEjjRlJwBWFz9CAjae14aAmehR6Sw56u21gkFG9D+mX2SiE1D6wEiXprD3/HSIF8CiRBTNlF6nozjvGWHBXIQGfViJXYgvsqkNN1mVKmNYoElQlZfOtlompXsy1wJmZcZpFN8bCzyO3c6XsEh9Bof4R60FzIWzTxdfbIUGvQUDpBTMzgWDUyJmS6n1lgKqUTwEd7YNOmoSGkRnylghE80LKSa/1/1s9Ec3O8C1G0/YP58x1SVjjbPCI4KVwOdWbA0SW8qYWP761s0tMdamkd9Ht/83Lny8kIiT0NGJYfZqAvbRjLJTH59biqRRE7Qn9mcx0b+KRacqTUYT/6FMmPPS/fnXyZ2stCyFGmSJ79O9+GoNpXsbW7ZHXp/uhAWQ1aKwA3No2JAMQlVnmzbAVH2VlvASrvU+iMj7RlcrhHtqAaK9VjsFDRitu1jijp7fY0uPaa/X4kM+8fUwPvmmNMAAsQG325qKVIacBzmSmMqpEKBC4z53ziWJWnOLx/OdiE+evbnMvoobIELzbPRpJtqBEK2oRs83J28gUw=
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
