dist: trusty
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: 
    token: HfQ+suX8syPTfrsLfy0pLTnVxPRvJWJSDOXKn6wuywaHs6bXHC7SBp23BWTiYIf6GdGoteC6AMPME+pGBKNZMJZTKOGXKSVdUm2Nd8lJGwH1DXiye5Cf0NeCLmrFWfFJPDMC2jK0PQHhUDvRV/lF/BHWyomuAeA5U/njM6jkbWyxqDBehoB4xa3va77s4idfLDF7xGUrE0mnKktZ9/MpBrs/uW2lcH4lc5il1cz24U8mafN1eSwJyGaTyUsHEo0BpcpSpy9FuWGRAUfTOcUSZ1+PVJoDA9UO3IfB8PB5T0rU5u6usw+YVPgKJl/uVg2ilGo9rPdfHwXTg4EV6LrYq1w8cNbc7IsuJPiG2wRJFlqA0v79FhEvjhrmH+7R9JnXKpxcbpW/kXGyWfeec5hICreaNYWp11SlqrTE5zHNk3klRWb2174SUfMh7ij1od8z8I8jf85fDKv4QvxGdOKKKzyt+UzjBh9twbiN5H9gd0D7Hm+Aj9xvTg6HraYPqGEuuvWfu7X6/BSvT6vZI/G5N8JbGNL+fT6njiuwHd6KF2sMlzGOYM6lKtC9OVJsmBI0JoQPbHsxKnUS75tUFMkc4d+v9U5TQdEQZIoY3bF2aDBWqtkNGZR/4f5DCwbhsf7T9k8Uz4SHZFPkjCfA0elnLqdFjTMYWuAQdoerCOjquMs=
    
branches:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- sonar-scanner -X -Dsonar.login=4d3d65e865d3c52cc7e1e764f8a8c867bce14181
