# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
