# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_auto_20170312_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cotacao.Item'),
        ),
    ]
