# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0004_auto_20170322_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.AddField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='cotacao.Pedido'),
        ),
    ]
